name: CI Pipeline 
on:
 push:
  branches:
  - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and test application
        run: |
         chmod +x mvnw
         ./mvnw install
  package:
   name: Package and Publish Image
   needs: [build]
   runs-on: ubuntu-20.04
   steps:
   - name: Check out repository
     uses: actions/checkout@v2
   - name: Set up JDK 11
     uses: actions/setup-java@v1
     with:
      java-version: 11
   - name: Login to DockerHub
     uses: docker/login-action@v1
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_TOKEN }}
   - name: Containerize
     run: |
      chmod +x mvnw
      ./mvnw package
   - name: Push to Docker Hub
     with:
      context: ./
      file: ./Dockerfile
      run: docker push nojaa/catalog-service:0.0.1-SNAPSHOT
